### PR TITLE
add metadata for already existing bio.tools packages

### PR DESCRIPTION
**Pull request by bgruening**
This PR was done by mapping bioconda recipes which are annotated with bio.tool IDs to this repo. We assume that the bio.tools ID is correct on the bioconda side.

### CODE REVIEW

**Comment by bgruening** [comment]
Those matches were done by pure bio.tools-ID matching ... if there is no error, this means over 1000 packages have been annotated with bio.tools. If that is true, this would be amazing!

**Comment by bgruening** [comment]
@albangaignard do you wanna merge this one? :)

**Comment by matuskalas** [comment]
Or are you anyway only using the second option inside Bioconda recipes itself, and adding `biotools_id: xyz` only for the sake of this **bio-tools/contents** repo?

##### Bonus)

It would also be super nice to have the Bioconda package name/id here in **bio-tools/contents**:
```
identifiers:
- biotools: a4base
- bioconda: bioconductor-a4base
```

**Comment by matuskalas** [comment]
Ok, I see that the Bioconda package name is always in `name: bioconductor-a4base`.

Any conclusive comments on these IDs and their representation (biotoolsID, biocondaName)? Merge as is?

**Comment by bgruening** [comment]
@matuskalas whatever you prefer! :)

**Pull request merged**
