### PR TITLE
TEST BIOCONTAINERS DO NOT MERGE!!!!

### PR DESCRIPTION
**Pull request by osallou**

### CODE REVIEW

**Comment by osallou** [comment]
@joncison this is a test for biocontainers to add a *download* info when biocontainers metadata gets a *biotools* link

Is it fine for you?

It is manual scripting for now, but I expect then to automate this in our CI. Each new/updated tool would add a download info if biotools entry is known (and exist)
Would not work, yet, for new tools (not known by biotools)

**Comment by osallou** [comment]
once PR data is validated by @joncison  , I can add to biocontainers CI automatic pull requests
It may cause at first some *spam* but this repo is a test repo, so should be fine

**Comment by bgruening** [comment]
@osallou the linter will take time, at least on this level. Let's do the following, can you create a biocontainers.yml file next to the other file ... this is your playground and you can merge/commit/update things into this file as you need.
Similarly Bioconda will have a bioconda.yml file.

@hansioan can then parse the content if he needs it for bio.tools.

Later we can merge it into the main file if @joncison has updated the schema or the linter, but for the time being we aggregating content.

Thanks!

**Comment by osallou** [comment]
But should keep the PR model or should we push commits directly to the repo?

Le jeu. 21 nov. 2019 à 13:57, Björn Grüning <notifications@github.com> a
écrit :

**Comment by bgruening** [comment]
Please keep the PR model. Thanks!

**Comment by osallou** [comment]
ok, I have activated PR on our Jenkins to create a biocontainer.json on updated tools to add a new "download" in the same way. Will check on further updates

**Pull request closed without merging**
