### PR TITLE
separate commit message and label

### PR DESCRIPTION
**Pull request by redmitry**

### CODE REVIEW

**Review by OlegZharkov — COMMENTED** [review]
Hi @redmitry thanks for the PR!
`import-changes.sh` is supposed to create a PR on this repository. Do you have an example? If not, can you please run this pipeline on your fork and check if this script works fine and creates the PR correctly?

**Comment by redmitry** [comment]
Hi, Oleg
Sorry for the delay. Yes I did the fork on my repo, so you can check action script and resulted PR.

**Comment by redmitry** [comment]
Here is an action script:
https://github.com/redmitry/content/edit/master/.github/workflows/openebench-import.yaml

**Review by hmenager — APPROVED** [review]
Usage is pretty straightforward, as exemplified in:
https://github.com/redmitry/content/blob/93fdd43eb54089b5580e89c9215a3a2739e0bf7b/.github/workflows/openebench-import.yaml#L53

You can now pass 3 parameters instead of 2 to the script: 
(1) is a PR currently open on that repo?
(2) commit message (new)
(3) commit "tag" that identifies it (e.g. open-ebench)

Unless @OlegZharkov can spot something that doesn't look right, I suggest we merge this one and transfer this version of the code to *https://github.com/bio-tools/content-ecosystem-utils/blob/main/scripts/git-utils/import-changes.sh*

**Comment by hmenager** [comment]
@redmitry can you push this version of the code to https://github.com/bio-tools/content-ecosystem-utils ?

**Pull request merged**
