### PR TITLE
new tools from Bioconda

### PR DESCRIPTION
**Pull request by bgruening**
This add new bioconda yaml files, for tools that are currently missing from bio.tools.

We mapped bioconda-recipes that are annotated with bio.tools IDs to this repo ... if there was no mapping but in bioconda there was actually a bio.tools ID annotated ... we create here a new folder.

It is strange in the first place that this is happening. It can be because:

* bioconda contributors just add non-existing bio.tool IDs
* bio.tool IDs got removed
* the content repo is not up to date

I assume the first option. Eitherway, I think those tools are valid and should be merged ... later also added to bio.tools.

### CODE REVIEW

**Comment by bgruening** [comment]
I prefer yaml because of readability. But I'm happy to be overruled ...

For the naming of the file, maybe a prefix makes grepping, globbing easier?

**Comment by hansioan** [comment]
I would prefer JSON as it works well with front end JavaScript based code. But I am sure we can run some automated code to have all the formats that we want. 

Regarding the naming strategy, all I know is that we need one, it will become harder and harder to distinguish files in the future, I already had problems with files. So this is something we can discuss

**Comment by redmitry** [comment]
Yaml is not the first citizen in Java, neither java has grep :D ...
This is a tradeoff between readability and more formal parsing.

**Comment by bgruening** [comment]
What is Java? ;)

**Comment by hmenager** [comment]
does anyone object to merging this one now?

**Comment by bgruening** [comment]
Me not ... :)

**Comment by matuskalas** [comment]
As I promised, I will also go through all these "dubious" biotoolsIDs, and fix them on the Bioconda side (and possibly/occassionally also in bio.tools). It's pretty much on the top of my list.

Nothing against merging now, if you want. Or waiting until it's fixed in Bioconda.

**Comment by hansioan** [comment]
See https://github.com/bio-tools/content/issues/52
for a list of bio.tools IDs found in Bioconda recipes that are not in bio.tools

**Pull request closed without merging**
